server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://172.18.248.2:3306/subworld
    username: flaim
    password: "root"
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  messages:
    basename: messages
  web:
    locale: en

app:

  token:
    secret: r5QgSFRyV8L9f3wEMBZY2Xonkize0txGhW7COmND6qp
    expiration-hours: 720

  uploads:
    base-dir: ./uploads

  skins:
    directory: uploads/skins
    url-prefix: /skins
    default-skin: default_skin.png
    max-size-mb: 5

  avatars:
    directory: uploads/avatars
    url-prefix: /avatars
    default: default_avatar.png
    size: 512
